%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% VIEWPixx Pixel Mode and audio latency validation
%
% This script measures and calibrates the temporal relationship between a
% VIEWPixx Pixel Mode trigger and the physical onset of an auditory
% stimulus. It is intended to determine the timing compensation required
% for an auditory experiment before the final timing values are transferred
% to the corresponding experiment script.
%
% Audio initialization is handled by initialize_audio_output.m, which
% prompts the user to select either the desktop Realtek headphone output
% or the RME Babyface Analog 3/4 output and opens the selected device using
% the standard PsychPortAudio configuration.
%
% The script presents every audio file contained in:
%
%     C:\Users\HoltLabUsers\Scripts\Audio_test
%
% Each audio file is presented 10 times consecutively. For every
% presentation, audio playback is scheduled together with a three-frame
% VIEWPixx Pixel Mode trigger. The trigger is generated by a 40 x 40 pixel
% region in the upper-left corner of the display using RGB [128 0 0].
% Pressing ESC at any time aborts the validation.
%
% The validation must be recorded simultaneously using BrainVision
% Recorder 2 in the Recording computer. The resulting EEG recording is then 
% analyzed using spectrogram_matching.m. This identifies the recorded
% position of the beginning of the audio file (FileStart) and the onset of
% audible content (FirstAudio). These values are compared with the physical
% Pixel Mode markers stored in the corresponding .bvrm file.
%
% The primary synchronization measure is:
%
%     FirstAudio - Pixel Mode
%
% because Pixel Mode is intended to mark the physical onset of audible
% stimulation rather than the beginning of the audio file itself.
%
% AUDIO TIMING COMPENSATION
% -------------------------
% Two timing components are defined separately in this script:
%
%     audioLagCompensation
%         Compensates for the physical timing offset associated with the
%         selected audio pathway. Separate values are maintained for the
%         Realtek and Babyface pathways.
%
%     leadingSilenceCompensation
%         Compensates for any silent interval between FileStart and
%         FirstAudio contained within the stimulus file.
%
% The final PsychPortAudio LatencyBias is calculated as:
%
%     LatencyBias = audioLagCompensation + leadingSilenceCompensation
%
% Positive LatencyBias values move physical audio earlier relative to
% Pixel Mode, whereas negative values move physical audio later.
%
% For the currently validated Babyface configuration:
%
%     RME output               = Analog 3/4
%     Backend                  = Windows WASAPI
%     Sample rate              = 48000 Hz
%     RME buffer               = 512 samples
%     audioLatencyClass        = 1
%     startLeadTime            = 0.200 s
%     babyfaceLagCompensation  = +0.005 s
%
% IMPORTANT:
% The timing-compensation values must not be assumed to apply to a new
% experiment or hardware configuration without validation. Changes to the
% audio pathway, audio-device configuration, stimulus leading silence, or
% relevant timing parameters require the Pixel Mode-to-audio relationship
% to be measured again using this script and spectrogram_matching.m.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Clean everything
sca;
clear;
clc;
close all

% Initialize and select the audio pathway
[cfg,pahandle] = initialize_audio_output;

% Emergency exit
KbName('UnifyKeyNames');
escapeKey = KbName('ESCAPE');

% Configure Psychtoolbox
Screen('Preference','SkipSyncTests',0);
Screen('Preference','VisualDebugLevel',0);

% VIEWPixx/ViewSonic in current Windows/PTB layout
screenNumber = 2; % Measured monitor refresh interval = 8.333 ms [120 Hz]
black = BlackIndex(screenNumber);
[window, ~] = Screen('OpenWindow', screenNumber, black);
HideCursor;
ifi = Screen('GetFlipInterval', window);
pixelRect    = [0 0 40 40];
triggerColor = [128 0 0];

% Timing precision
startLeadTime = 0.200; % Schedule visual and audio 200 ms in advance

% Audio timing compensation - these values are kept separate intentionally:
%   babyface or realtek audioLagCompensation:
%   Compensates for the physical delay introduced by the selected audio
%   pathway. This value depends on the audio device/configuration
%   You always need to check which are the delays for your experiment!!
%
%   leadingSilenceCompensation: compensates for the silent interval between 
%   FileStart and FirstAudio of an audio file (if any). In the case of my
%   current experiment, it has a 50 ms lag between the start if every audio 
%   file and every audio onset
% 
% The final PsychPortAudio LatencyBias is calculated as the sum of both

babyfaceLagCompensation = 0.005;  % Babyface WASAPI @ 512 samples
realtekLagCompensation  = -0.028;  % Realtek WASAPI
leadingSilenceCompensation = 0.050; % 50 ms FileStart -> FirstAudio

% Select audio-path-specific timing compensation
if strcmp(cfg.audioPath,'realtek')
    
    % Desktop Realtek headphone output -> StimTrak
    audioLagCompensation = realtekLagCompensation;

elseif strcmp(cfg.audioPath,'babyface')

    % RME Babyface Analog 3/4, WASAPI, 512-sample RME buffer
    audioLagCompensation = babyfaceLagCompensation;

else

    error('Unknown audio pathway: %s',cfg.audioPath);
    
end

% Total audio timing correction:
% physical audio-path lag + leading silence within the audio file
latencyBias = audioLagCompensation + leadingSilenceCompensation;
PsychPortAudio('LatencyBias', pahandle, latencyBias);

% Check PTB-estimated output latency
audioStatus = PsychPortAudio('GetStatus',pahandle);

fprintf('\n');
fprintf('Predicted audio latency: %.3f ms\n', ...
    audioStatus.PredictedLatency * 1000);

Priority(MaxPriority(window));

% Locate every audio file
audioFolder = 'C:\Users\HoltLabUsers\Scripts\Audio_test';
audioFiles = dir(fullfile(audioFolder,'*.flac'));

if isempty(audioFiles)
    
    Priority(0);
    PsychPortAudio('Close',pahandle);
    sca;
    ShowCursor;
    
    error('No audio files were found in:\n%s',audioFolder);

end

% Presents each available audio file 10 times
trialOrder = repelem(1:numel(audioFiles),10);
nTrials = numel(trialOrder);

% Create the played-sequence report
sequenceFile = fullfile(audioFolder,'played_sequence.txt');
fidSequence = fopen(sequenceFile,'w');
fprintf(fidSequence,...
    'VIEWPixx audio latency validation\n\n');

fprintf('\n');
fprintf('=====================================================\n');
fprintf('VIEWPixx Pixel Mode + audio latency validation\n');
fprintf('=====================================================\n');
fprintf('Audio device : %s\n',cfg.audioDeviceName);
fprintf('Device index : %d\n',cfg.audioDeviceIndex);
fprintf('Sample rate  : %d Hz\n',cfg.sampleRate);
fprintf('Latency bias : %+.3f ms\n',latencyBias * 1000);
fprintf('Audio files  : %d\n',numel(audioFiles));
fprintf('Trials       : %d\n',nTrials);
fprintf('Press ESC to abort.\n\n');
fprintf('Audio lag compensation      : %+.3f ms\n', audioLagCompensation * 1000);
fprintf('Leading silence compensation: %+.3f ms\n', leadingSilenceCompensation * 1000);
fprintf('Total latency bias          : %+.3f ms\n', latencyBias * 1000);

try

    % Run the validation trials
    for trial = 1:nTrials

        audioName = audioFiles(trialOrder(trial)).name;
        audioFile = fullfile(audioFolder,audioName);

        fprintf('Trial %02d : %s\n', ...
            trial, audioName);

        fprintf(fidSequence,...
            'Trial %02d : %s\n',...
            trial, audioName);

        % Load the current audio file
        [y,fs] = audioread(audioFile);

        if fs ~= cfg.sampleRate
            error('%s is not sampled at 48 kHz.',audioName);
        end

        % Create the playback buffer
        if size(y,2)==1

            buffer = [y'; y'];

        else

            buffer = y(:,1:2)';

        end

        % Present a 2 s baseline
        Screen('FillRect',window,black);
        Screen('Flip',window);

        t0 = GetSecs;

        while GetSecs - t0 < 2

            [pressed,~,keys] = KbCheck;

            if pressed && keys(escapeKey)

                error('Validation aborted by user.');

            end

            WaitSecs('YieldSecs',0.005);

        end

        % Fill the audio buffer
        PsychPortAudio('FillBuffer',pahandle,buffer);
        
        % Schedule simultaneous audio playback and Pixel Mode trigger
        startTime = GetSecs + startLeadTime;
        PsychPortAudio('Start',pahandle,1,startTime,0);

        % Present the Pixel Mode trigger
        Screen('FillRect',window,black);
        Screen('FillRect',window,triggerColor,pixelRect);
        
        vbl = Screen('Flip',window,startTime);

        % Wait until the audio hardware confirms playback
        audioStatus = PsychPortAudio('GetStatus',pahandle);

        while audioStatus.StartTime <= 0

            WaitSecs('YieldSecs',0.001);
            audioStatus = PsychPortAudio('GetStatus',pahandle);

        end

        for k = 2:3

            Screen('FillRect',window,black);
            Screen('FillRect',window,triggerColor,pixelRect);

            vbl = Screen('Flip',window,vbl + ifi);

        end

        Screen('FillRect',window,black);
        Screen('Flip',window);

        % Wait until playback finishes
        audioStatus = PsychPortAudio('GetStatus',pahandle);
        
        while audioStatus.Active
        
            [pressed,~,keys] = KbCheck;
        
            if pressed && keys(escapeKey)
                error('Validation aborted by user.');
            end
        
            WaitSecs('YieldSecs',0.005);
            audioStatus = PsychPortAudio('GetStatus',pahandle);
        
        end

        PsychPortAudio('Stop',pahandle);

        % Present a 2 s inter-trial interval
        t0 = GetSecs;

        while GetSecs - t0 < 2

            [pressed,~,keys] = KbCheck;

            if pressed && keys(escapeKey)

                error('Validation aborted by user.');

            end

            WaitSecs('YieldSecs',0.005);

        end

    end

    fclose(fidSequence);
    fprintf('\nValidation completed successfully.\n');

catch ME

    if exist('fidSequence','var') && fidSequence > 0
        fclose(fidSequence);
    end

    PsychPortAudio('Close',pahandle);
    Priority(0);
    sca;
    ShowCursor;

    rethrow(ME);

end

% Close PsychPortAudio and the display
PsychPortAudio('Close',pahandle);
Priority(0);
sca;
ShowCursor;

